-- drop table who_to_follow;
-- CREATE TABLE who_to_follow (
--        who_id int NOT NULL AUTO_INCREMENT,
--        username varchar(255) DEFAULT NULL,
--        avatar_icon varchar(255) DEFAULT NULL,
--        handle varchar(255) DEFAULT NULL,
--        PRIMARY KEY (who_id)
-- );
--
--
-- INSERT INTO `Tuitter`.`who_to_follow`
-- (`who_id`, `username`, `handle`,`avatar_icon`  )  values (null, 'Java', 'java', '/imgs/java.png');
--
-- INSERT INTO `Tuitter`.`who_to_follow`
-- (`who_id`, `username`, `handle`,`avatar_icon`  )  values (null, 'Relaivity Space', 'Relativity Space', '/imgs/relativity-space.jpg');
--
-- INSERT INTO `Tuitter`.`who_to_follow`
-- (`who_id`, `username`, `handle`,`avatar_icon`  )  values (null, 'Virgin Galactic', 'Virgin', '/imgs/virgin.png');
--
-- INSERT INTO `Tuitter`.`who_to_follow`
-- (`who_id`, `username`, `handle`,`avatar_icon`  )  values (null, 'NASA', 'NASA', '/imgs/nasa.png');
--
-- INSERT INTO `Tuitter`.`who_to_follow`
-- (`who_id`, `username`, `handle`,`avatar_icon`  )  values (null, 'Tesla', 'TSLA', '/imgs/tesla.png');
--
-- select * from Tuitter.who_to_follow;
--
-- SELECT * FROM Tuitter.users;
--
-- insert into Tuitter.users values (null, '/public/imgs/banner.jpg','Factulty, Software Engineer', '4/2009', '1996-02-16','Jose', '312', '180','Annunziato','Houston,Texas', '/imgs/jose.png','jannunzi','google.com');
-- insert into Tuitter.users values (null, '/public/imgs/banner.jpg','Fidelity Software Engineer', '4/2009', '1996-02-16','Alex', '312', '180','Thammavongsa','Houston,Texas', '/imgs/jose.png','athammav','fidelity.com');
-- insert into Tuitter.users values (null, '/public/imgs/banner.jpg','Fidelity Software Engineer', '4/2009', '1996-02-16','Alvin', '312', '180','Chandy','Houston,Texas', '/imgs/jose.png','achandy','fidelity.com');


-- INSERT INTO Tuitter.tweets (topic, username, verified, handle, time, title, tweet, logo_image, avatar_image,tweeted_by_user_id )
-- VALUES ('Web Development', 'ReactJs', 1, 'ReactJS', '2h', 'React.js is a component based front end library that makes it very easy to build Single Page Applications or SPAs',
--     'Lorem Lorem Lorem ipsum dolor sit amet, consectetur adipiscing elit', '../../../images/react-blue.png','../../../images/react-blue.png','1');
--
--
-- INSERT INTO Tuitter.tweets (topic, username, verified, handle, time, title, tweet, logo_image, avatar_image,tweeted_by_user_id )
-- VALUES ('Brazilian Jiu Jitsu', 'bjj', 1, 'bjj', '2h', 'MMA Junkie Reports',
--         'Ryan Hall wins and dominates the BJJ game in MMA', '../../../images/react-blue.png','../../../images/react-blue.png','2');
--
-- INSERT INTO Tuitter.tweets (topic, username, verified, handle, time, title, tweet, logo_image, avatar_image,tweeted_by_user_id )
-- VALUES ('Brazilian Jiu Jitsu', 'bjj', 1, 'bjj', '2h', 'MMA Junkie Reports',
--         'Jorge Masvidal needs to retire to save his stock', '../../../images/react-blue.png','../../../images/react-blue.png','2');
--
--
-- select * from Tuitter.tweets;